#!/bin/sh
#
# Install a replacement script for /usr/sbin/sendmail.
# Also makes a back-up of the original executable.

today_yyyy_mm_dd () {
  local today=$(date +%Y-%m-%d)
  case "$today" in
    [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]) ;;
    *)  echo "date +%Y-%m-%d failed: $today"; exit 1 ;;
  esac
  echo "$today"
}

make_backup () {
  local src="$1"

  local today=$(today_yyyy_mm_dd)

  local dest=$(mktemp -q "$src-$today-XXXXX")
  case "$?" in
    0) ;;
    *) echo "unable to create temporary file in $dir"; exit 1;;
  esac

  /bin/cp "$src" "$dest"
  if ! cmp -s "$src" "$dest"; then
    echo "backup of $src failed"
    exit 1
  fi

  echo "Saved $src to $dest"
}

install_replacement () {
  local dest="$1"
  local replacement="$2"
  local perform_chmod="$3"

  if [ -z "$dest" -o -z "$replacement" ]; then
    echo "install_sendmail: bad usage"
    exit 1
  fi

  if [ ! -e "$replacement" ]; then
    echo "replacement script '$replacement' not found"
    exit 1
  fi

  local destdir=$(dirname "$dest")

  if [ ! -d "$destdir" ]; then
    echo "$destdir is not a directory"
    exit 1
  fi

  if [ ! -w "$destdir" ]; then
    echo "$destdir not writable - not running as root?"
    exit 1
  fi

  if [ -e "$dest" ]; then
    make_backup "$dest"
  fi

  cp "$replacement" "$dest"
  if [ -n "$perform_chmod" ]; then
    chmod a+rx,o-w,u+s "$dest"
  fi
  echo "installed $replacement at $dest"
}

case "$1" in
  "doit")  set -x; set -e; install_replacement "/usr/sbin/sendmail" "./fake_sendmail" ;;
   *)  echo "Use: $0 doit" ; exit 1;;
esac

